#!/bin/sh

##
## Scratchpad script
##

main() {
  local state=$(/usr/bin/systemctl --user show -p ActiveState 'foot@scratchpad.service' | /usr/bin/cut -d= -f2)

  if [ "$state" = 'failed' ]; then
    /usr/bin/systemctl --user reset-failed 'foot@scratchpad.service' &&
      state='inactive'
  fi

  /usr/bin/hyprctl dispatch -- togglespecialworkspace scratchpad

  if [ "$state" = 'inactive' ]; then
    command="new-session -s 0"

    if \
      /usr/bin/tmux \
        -S /run/user/${UID}/tmux-scratchpad \
        has-session \
        -t scratchpad 2>/dev/null \
    ; then
      command="attach-session -t scratchpad"
    fi

    /usr/bin/systemd-run \
      --user \
      --slice='foot.slice' \
      --unit='foot@scratchpad' \
      --nice=15 \
      -- \
      /usr/bin/foot \
      --app-id="foot.scratchpad" \
      /usr/bin/tmux \
      -S /run/user/${UID}/tmux-scratchpad \
      $command
  fi
}

main "$@"
