#!/bin/sh

_handle() {
  if [[ ${1:0:11} == "workspace>>" ]]; then
    _workspace="${1:11:2}"

    $XDG_SCRIPTS_HOME/hypr/wallpaperrc --workspace $_workspace
  fi
}

socat -u "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - | while read -r line; do _handle "$line"; done
