#!/bin/bash

##
## Clipboard
##


main() {
  local popup="0"

  while [ "$#" -gt 0 ]; do
    case "$1" in
      -p|--popup) popup="1"; shift 1 ;;

      *) echo "Unknown argument: $1"; exit 1 ;;
    esac
  done

  _popup() {
    focused_output=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused==true).name')
    output_dimensions=$(swaymsg -t get_outputs | jq -r --arg focused_output "$focused_output" '.[] | select(.name==$focused_output) | "\(.rect.width) \(.rect.height)"')

    width=$(echo $output_dimensions | awk '{printf "%.0f", $1 * 0.5}')
    height=$(echo $output_dimensions | awk '{printf "%.0f", $2 * 0.5}')

    /usr/bin/swaymsg "[app_id=\"foot.power\"] scratchpad show" > /dev/null 2>&1 \
      && /usr/bin/swaymsg "[app_id=\"foot.power\"] resize set width ${width}px, resize set height ${height}px, move position center" > /dev/null 2>&1 \
      && exit 0

    /usr/bin/foot \
        --app-id foot.power \
        --font 'FiraCode Nerd Font:size=16' \
        --window-size-pixels "${width}x${height}" \
        $HOME/.scripts/sway/clipboardrc
  }

  if [[ "$popup" == "1" ]]; then
    _popup || exit 1 && exit 0
  fi

  local choice="$(/usr/bin/cliphist list | /usr/bin/fzf --prompt=' ' --pointer='' --color='bg+:#1e1e2e' -d $'\t' --with-nth 2)"

  if [ -z "$choice" ]; then
    echo "No choice made: exiting..." \
      && exit 1
  fi

  echo "$choice" | /usr/bin/cliphist decode | /usr/bin/wl-copy
}

main $@
