#!/bin/sh

##
## Power
##


main() {
  local popup="0"

  while [ "$#" -gt 0 ]; do
    case "$1" in
      -p|--popup) popup="1"; shift 1 ;;

      *) echo "Unknown argument: $1"; exit 1 ;;
    esac
  done

  _items() {
    echo "Suspend"
    echo "Reboot"
    echo "Power off"
  }

  _popup() {
    focused_output=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused==true).name')
    output_dimensions=$(swaymsg -t get_outputs | jq -r --arg focused_output "$focused_output" '.[] | select(.name==$focused_output) | "\(.rect.width) \(.rect.height)"')

    width=$(echo $output_dimensions | awk '{printf "%.0f", $1 * 0.5}')
    height=$(echo $output_dimensions | awk '{printf "%.0f", $2 * 0.5}')

    /usr/bin/swaymsg "[app_id=\"foot.power\"] scratchpad show" \
      && /usr/bin/swaymsg "[app_id=\"foot.power\"] resize set width ${width}px, resize set height ${height}px, move position center" \
      && exit 0

    /usr/bin/foot \
      --app-id foot.power \
      --font 'FiraCode Nerd Font:size=16' \
      --window-size-pixels "${width}x${height}" \
      $HOME/.scripts/sway/powerrc
  }

  if [ "$popup" = "1" ]; then
    _popup || exit 1 && exit 0
  fi

  local choice="$(_items | /usr/bin/fzf --prompt=' ' --pointer='' --color='bg+:#1e1e2e')"

  if [ -z "$choice" ]; then
    echo "No choice made: exiting..." \
      && exit 1
  fi

  case "$choice" in
    "Power off") /usr/bin/systemctl poweroff ;;
    "Reboot") /usr/bin/systemctl reboot ;;
    "Suspend") /usr/bin/systemctl suspend ;;
  esac
}

main "$@"
